name: Cross Platform Verification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        profile: ["", "--profile=release", "--profile=release-opt"]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build ${{ matrix.profile }} --verbose
    - name: Run tests
      run: cargo test ${{ matrix.profile }} --verbose
